# Generated by Django 4.0 on 2022-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='agents',
            field=models.ManyToManyField(blank=True, to='user.Agent'),
        ),
    ]
