# Generated by Django 4.0.4 on 2022-06-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='booked_quantity',
            field=models.IntegerField(default=0, verbose_name='Booked Quantity'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='Total Quantity'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine', verbose_name='Vaccine'),
        ),
    ]
