# Generated by Django 4.0 on 2022-04-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_center_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='agents',
        ),
    ]
