# Generated by Django 4.0.2 on 2022-03-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_rename_available_quantity_storage_total_quantity'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdate',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
    ]
