# Generated by Django 4.0.3 on 2022-04-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='center',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='dose_number',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='vaccine',
        ),
    ]
