# Generated by Django 4.0.2 on 2022-03-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
        ('vaccination', '0002_vaccinationdate_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdate',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
    ]
