# Generated by Django 4.0.3 on 2022-04-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_remove_vaccination_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
