# Generated by Django 4.0.4 on 2022-06-16 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0002_alter_storage_booked_quantity_alter_storage_center_and_more'),
        ('vaccination', '0002_alter_vaccination_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccination_campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='is_vaccinated',
            field=models.BooleanField(default=False, verbose_name='Is Vaccinated'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.slot', verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='vaccination_campaign',
            name='agents',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Agents'),
        ),
        migrations.AlterField(
            model_name='vaccination_campaign',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='center.center', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='vaccination_campaign',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='vaccination_campaign',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='vaccination_campaign',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine', verbose_name='Vaccine'),
        ),
    ]
