# Generated by Django 4.0.2 on 2022-03-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_vaccinationdate_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationdate',
            name='slots',
        ),
        migrations.AddField(
            model_name='slot',
            name='vaccination_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationdate'),
        ),
    ]
