# Generated by Django 4.0 on 2022-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_admin_user'),
        ('vaccination', '0003_vaccination_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination_campaign',
            name='agents',
            field=models.ManyToManyField(blank=True, to='user.Agent'),
        ),
    ]
