# Generated by Django 4.0.5 on 2022-06-17 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0002_alter_storage_booked_quantity_alter_storage_center_and_more'),
        ('vaccine', '0001_initial'),
        ('vaccination', '0003_alter_vaccination_campaign_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccination_Campaign',
            new_name='Campaign',
        ),
    ]
