# Generated by Django 4.0.2 on 2022-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_rename_vaccinationdate_vaccination_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination_campaign',
            name='date',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='vaccination_campaign',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Vaccination Campaign End Date'),
        ),
        migrations.AddField(
            model_name='vaccination_campaign',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Vaccination Campaign Start Date'),
        ),
    ]
