# Generated by Django 4.0.4 on 2022-06-09 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xyz', to=settings.AUTH_USER_MODEL, verbose_name='Email Address'),
        ),
    ]
