# Generated by Django 4.0.5 on 2022-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
                verbose_name="Blood Group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identity_document_type",
            field=models.CharField(
                choices=[
                    ("Voter Id", "Voter ID"),
                    ("Passport", "Passport"),
                    ("Citizenship Number", "Citizenship Number"),
                ],
                max_length=32,
                null=True,
                verbose_name="Identity Document Type",
            ),
        ),
    ]
