# Generated by Django 4.0.3 on 2022-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(choices=[('Doctor', 'Docter'), ('Nurse', 'Nurse'), ('Helper', 'Helper')], max_length=32, verbose_name='Agent Type'),
        ),
    ]
