# Generated by Django 4.0.4 on 2022-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_agent_user_remove_patient_user_delete_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_document_type',
            field=models.CharField(choices=[('Voter_Id', 'Voter ID'), ('passport', 'Passport'), ('Citizenship_Number', 'Citizenship Number')], max_length=32, null=True, verbose_name='Identity Document Type'),
        ),
    ]
