# Generated by Django 4.0.3 on 2022-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_photo_alter_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/profileImage/', verbose_name='Profile Picture'),
        ),
    ]
