# Generated by Django 4.0.4 on 2022-05-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=320, unique=True, verbose_name='Email Address'),
        ),
    ]
