# Generated by Django 4.0 on 2022-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_condition', '0001_initial'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='ineligible_medical_condition',
            field=models.ManyToManyField(blank=True, to='medical_condition.Medical_Condition'),
        ),
    ]
