name: Django Test Cases Check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }} 
      DEBUG: ${{ secrets.DEBUG }} 

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip
    - name: Run Test Cases
      run: |
        pip install virtualenv
        virtualenv env
        source env/bin/activate
        export SECRET_KEY=$SECRET_KEY
        export DEBUG=$DEBUG
        pip install -r requirements.txt
        cd mysite
        python manage.py test
